mas-bandwidth/yojimbo

yojimbo_common.h
Was 32786, changed to 32768 (function not referenced, so wasn't causing
problems).
=> Fixed max legit sequence gap in sequence_difference

yojimbo_address.cpp
This is a small consistency nitpick. I noticed in Address::Clear(), ipv6 was being set to 0 but ipv4 was not.
=> Set both ipv4 and ipv6 to 0 in Address::Clear()

yojimbo_serialize.h
Visual Studio complains on the reading path for all these macros, as the serialize function is passed an uninitialized variable by reference.
`warning C4700: uninitialized local variable 'uint32_value' used`
=> Silence lots of MSVC C4700 warnings

yojimbo_bitpack.h
assert() checks NDEBUG not DEBUG, so associate parts should
also check NDEBUG.
Closes networkprotocol/libyojimbo#27
=> Check NDEBUG instead of DEBUG in yojimbo_bitpack.h

yojimbo_channel.cpp, yojimbo_client.cpp, yojimbo_client.h, yojimbo_serialize.h, yojimbo_server.cpp, yojimbo_server.h
Wasn't sure if I should split these into multiple pull requests, so they're all in separate commits at least.
1. Fixes two issues with `serialize_enum` macro in yojimbo_serialize.h (lack of cast to uint32_t from input enum, and setting output value to value instead of int_value).
2. Fixes bug in `UnreliableOrderedChannel::GetPacketData(...)` where the channel ID of the outgoing ChannelPacketData was not set. If using more than 1 channel, and the Unreliable channel was not channel 0, this caused all sorts of asserts.
3. Added functionality to allow sending Messages to specific channels in Server and Client classes. Using this functionality in my own project is what had me find the issue in (2).
=> Bug fixes to serialize_enum(...) and UnreliableOrderedChannel::GetPacketData(...); Add missing functionality to Server and Client

yojimbo_server.cpp
The size and set arguments for memset are swapped in this case.  This pull request is simply swapping them to their correct positions.  I reviewed the other invocations of memset and did not find any more errors like this.
=> fix for memset typo in Server::ResetCounters

yojimbo_client.h, yojimbo_server.h
Maybe there are more left. 
But I'm not using yojimbo namespace in any of my headers and it works now.
=> Fix missing namespace in server/client macros

yojimbo_config.h
If the `_CRT_SECURE_NO_WARNINGS` macro is already set, then any include of the yojimbo headers will result in a spam of C4005 warnings;
```
1>...\libyojimbo\yojimbo_config.h(31): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
1>  ...\libyojimbo\yojimbo_config.h(31): note: command-line arguments:  see previous definition of '_CRT_SECURE_NO_WARNINGS'
```
=> Silence possible C4005 warnings

yojimbo_config.h
Changes:
1. Search for little or big endian defines, don't assume either option by default. If detection fails - emit a compiler error
2. Possible to pass YOJIMBO_BIG_ENDIAN or YOJIMBO_LITTLE_ENDIAN from build environment
=> Better endianness detection

yojimbo_client_server_packets.h
Missing include in yojimbo_client_server_packets.h to be standalone
=> Fix compilation issue when including yojimbo_client_server_packets.h alone

android/ifaddrs/ifaddrs.c, android/ifaddrs/ifaddrs.h, yojimbo_address.cpp, yojimbo_network.cpp, yojimbo_sockets.cpp
Android ndk toolchain is missing `ifaddrs.h` for some reason. 
I've added implementation from here: https://github.com/morristech/android-ifaddrs
Not sure it is right to ship that header with yojimbo, because we don't have any build scripts or samples for Android. User must add `android/ifaddrs` to header search paths in the chosen build system. 
There is also `sockaddr_storage` that is redefined as a macro and I had to change include order so that system libraries go before yojimbo_address.h. 
Library works flawlessly on Android.
=> Compiles on Android

yojimbo_message.h
As the title says.
Don't want to have to const_cast messages just to be able to read the data.
=> Add a const getter for block message data

yojimbo_common.h
The following code:
```
rce->server->yj_transport = std::make_unique<yojimbo::NetworkTransport>(
yojimbo::GetDefaultAllocator(),
yojimbo::Address(),
PROTOCOL_VERSION,
cur_time
);
```
yields this error in GCC 6.3.1 on Linux
`error: call of overloaded ‘swap(yojimbo::NetworkTransport*&, yojimbo::NetworkTransport*&)’ is ambiguous`
It looks like the `swap` function in `yojimbo_common.h` is interfering with the swap function from the standard library.
This PR just removes the definition on C++11 or newer compilers using the `__cplusplus` macro. That being said, it's totally possible I'm doing something wrong, as both my C++ and knowledge of the standard are a little rusty these days.
Any thoughts?
Also thanks so much for this library, I expect to learn tons by studying and using it!
=> Avoid swap function redefinition

yojimbo_client.cpp
the Client.IsConnected() returned true, while still connecting.
=> fixed the connected while connecting bug

yojimbo.cpp, yojimbo.h
I'm not sure why, but it looks like the total number of message types was being subtracted by one. if I remove that subtraction, it seems to fix the issue.
=> fix for when we only have one message type

.travis.yml, docker/Dockerfile, yojimbo.cpp
As of mbedtls version 2.4.2 (though perhaps earlier as well)  [mbedtls/net.h is deprecated](https://github.com/ARMmbed/mbedtls/blob/2ab14bb2ca8cebc3175b076fa42c293a2bc72202/include/mbedtls/net.h#L30).
Changing yojimbo to use mbedtls/net_sockets.h instead, per deprecation message.
=> mbedtls/net.h is deprecated. Use mbedtls/net_sockets.h instead.

.travis.yml, BUILDING.md, docker/Dockerfile, matcher/Dockerfile, premake5.lua, valgrind/Dockerfile
- Upgraded libsodium to 1.0.16 (latest current release).
- Upgraded premake5 to 5.0.0 alpha 13 and fixed deprecation warnings
- Use make -j32 in Docker image builds to reduce build time
- Upgrade valgrind/Dockerfile (I missed it in my last set of changes)
- Use wildcard * in Dockerfiles and .travis to reduce version number redundancy (similar to what was done with premake5 before in some of the Dockerfiles).
1. premake5 --version (Premake Build Script Generator) 5.0.0-alpha13
1. premake5 clean
1. premake5 gmake
1. make
1. bin/test (ALL TESTS PASS)
1. premake5 valgrind (ALL TESTS PASS) (no leaks, ERROR SUMMARY: 40 errors from 5 contexts (suppressed: 0 from 0)). Full report here: [valgrind result.txt](https://github.com/networkprotocol/yojimbo/files/2583019/valgrind.result.txt)
1. premake5 …
=> Upgrade to libsodium 1.0.16, premake5 5.0.0 alpha 13, and speedup Docker image builds

premake5.lua
As of Lua 5.2, os.execute returns 3-tuple. In 5.1 and before it returned the status code. This change updates premake5.lua to use the Lua 5.2 definition of os.execute.
premake5 5.0.0 alpha 13 is using Lua 5.3.4.
=> Fix several of the premake5 commands that relied on os.execute.

yojimbo.cpp, yojimbo.h
Hello Glenn,
I'm currently testing yojimbo for my top-down shooter as it looks like a really solid network stack.
I already did some gameplay tests and I think I'll stay with this library for quite some time to come!
I made some commits along the way that I think could perhaps be useful.
The first commit makes the channels' ``HasMessagesToSend`` methods accessible to the library's user 
the same way that ``CanSendMessage`` methods are. 
One use-case I can think of if is the initial state of the world is reaally huge, say, it takes several seconds to transfer. 
The next server update, whether it's a delta-compressed snapshot or a list of inputs - 
might grow so huge during the initial transfer that it's probably best sent using another block message, so the server would simply check if the …
=> public HasMessagesToSend, unused field, fixed an assertion

test.cpp, yojimbo.cpp, yojimbo.h
Glenn,
As I had mentioned earlier, I finally got around to adding varint32 and varint64 methods for variable length serialization of integers. measure will be between 1 and 9 bytes, depending on size of number.
Serialization methods, and tests have been updated.
- Sky
=> added serialization of varints

premake5.lua
Use os.host() to get target os in docs action since os.get() is deprecated.
=> use os.host() instead of os.get() - premake5.lua

premake5.lua, yojimbo.h
This and the other two pull requests (https://github.com/networkprotocol/reliable/pull/25 and https://github.com/networkprotocol/netcode/pull/105) are useful because we're trying to fit yojimbo into an Unreal project, which always defines `NDEBUG` if you're using the release CRT. We'd like to be able to take advantage of debug features in yojimbo, so if there are separate debug (and release) flags for the projects, we can define these without modifying the engine.
In addition, these pull requests should all be no-op for existing users -- if you don't define the _DEBUG or _RELEASE symbols, we fall back to using NDEBUG to determine debug status.
=> Project specific debug defines

yojimbo.cpp, yojimbo.h
This just calls the already existing netcode_server_client_address.
This is similar to the already existing Server::GetClientId.
Feel free to close if no one wants this feature, but I needed it so I figured I'd put it here.
=> Add Server::GetClientAddress

yojimbo.cpp
Fix a crash if a call to serialize_xxx macro return false before the allocation of block.message or block.fragmentData in SerializeBlockFragment function.
The release of any of these uninitialized pointer will cause the crash in ChannelPacketData::Free function.
=> Fix crash in  ChannelPacketData::Free function

tlsf/tlsf.c
- Fix undefined behavior in some bit twiddling (mattconte/tlsf@deff9ab509341f264addbd3c8ada533678591905)
- Two fixes to large allocations (mattconte/tlsf@a1f743ffac0305408b39e791e0ffb45f6d9bc777, mattconte/tlsf@16b6a9657db78adde16993351a4adf2a402c0865)
=> Update tlsf to receive three fixes

yojimbo.cpp, yojimbo.h
In some use cases a more instantaneous, or less smoothed, RTT might be desirable.
=> Added RTT smoothing factor to Client/Server config.

yojimbo.cpp
...since compilers like MSVC assume allocation functions return 16-bit alignment.
This causes issues with messages that have fields aligned (via __declspec() or alignas()) to 16-bytes, since the compiler
assumes allocated structs will be placed on a 16-byte boundary, but tlsf_malloc() only guarantees an 8-byte alignment so
a member declared inside a Yojimbo message with 16-byte alignment might end up at an 8-byte boundary.
This has a tiny cost of the occasional additional 8-bytes of waste per allocation, but in practice I've seen this
to be within noise. Debugging an issue like this might be unobvious for non-senior engineers, so I think the cost is
justified.
=> Replaced tlsf_malloc() with tlsf_memalign(16)

yojimbo.cpp
Instead of directly calling `printf` and `exit`, use `yojimbo_printf`
and `yojimbo_assert` in the leak detection in `Allocator::~Allocator`.
This helps integrate better with client applications.
Also switch the `default_assert_handler` to use `yojimbo_printf`.
=> Leak detection: Use registered printf & assert

yojimbo.cpp
When running some tests I noticed that the `YojimboClient` would sometimes sets its state to `CLIENT_STATE_CONNECTED` before the server would execute the `OnServerClientConnected` callback. Looking at the current logic the `YojimboClient` sets the state to `CLIENT_STATE_CONNECTED` when the netcode state is `NETCODE_CLIENT_STATE_SENDING_CONNECTION_RESPONSE` rather than when it is `NETCODE_CLIENT_STATE_CONNECTED`.
This PR fixes that.
=> Fix YojimboClient state update logic

test.cpp, yojimbo.cpp, yojimbo.h
If there are over 32768 unreliable packets sent between reliable
messages, which can happen in under ten minutes at 60 fps, then the
sequence number of the next reliable message appears to be old,
causing an assertion failure. To avoid this, always interpret outbound
sequence values as newer than prior values.
Fixes #138
=> Fix assert from delay between reliable messages

yojimbo.cpp
Helps alleviate https://github.com/networkprotocol/yojimbo/issues/185 by providing a clear error message rather than silently failing to send reliable messages on the channel.
=> Assert when messages are too large to be sent

matcher/Dockerfile, matcher/README.md, matcher/go.mod, matcher/go.sum, matcher/main.go
Hey there, while updating my project to the latest `yojimbo` changes I noticed that the matcher code was removed. 
Years ago when I began using `yojimbo` in my projects I found the code in the matcher example extremely valuable for implementing the connection token logic. I am certain it is valuable to others as well.
If you are open to re-adding it, or putting it in its own repo, I've fixed up the `Dockerfile` and updated the code a little bit. The changes include: 
- Removed the `cgo` dependency requiring `libsodium`, the `golang.org/x/crypto` package now provides a native go implementation of the `crypto_aead_xchacha20poly1305_ietf_encrypt` function.
- Switch from the `gorilla/mux` router to `chi`. `chi` is a very lightweight http router that uses the go standard lib interfaces rather …
=> Add the matcher sample back to the repo

.github/workflows/ci.yml, include/yojimbo_server.h, include/yojimbo_server_interface.h, matcher/main.go, premake5.lua, source/yojimbo_server.cpp
Hey there. I noticed there was no method exposed for that in `yojimbo` to access the userdata inside the connection token, so I added one.
I also noticed that my `userdata` bytes were "shifted" and including the trailing 12 bytes of the `ServerToClientKey` . After some debugging I realized that the `writeAddresses` function in the matcher code always increments the offset by 19, whether it is IPV4 or IPV6, but  `netcode` it reads only as many bytes as needed. So I fixed that too.
Cheers
=> Expose `GetClientUserData` on YojimboServer class. Fix address serialization bug in matcher code.

soak.cpp
It doesn't hurt anything but y'know.. made me do a double-take while reading. I left the other call in main(), since that's where srand() is called in all of the other tests.
=> Remove redundant srand call

source/yojimbo_connection.cpp
Weird bug. Remove `return` keyword.
=> You can't return a value from a void function
